### ISSUE TITLE
[BUG] 클로드 사이드바 아이콘 위로 설정하면 다른 곳들에서 사라지는 현상

### ISSUE THREAD

**Issue by jiwoochris** [ai-surfers/promptmate-chrome-extension#61]
## ✔️ 어떤 기능인가요?
클로드 사이드바 아이콘 위로 설정하면 다른 곳들에서 사라지는 현상
(위로 날라가버립니다)

## ✔️ 상세 내용
버전: https://github.com/ai-surfers/promptmate-chrome-extension/pull/60
브라우저: Chrome

https://github.com/user-attachments/assets/ec868f63-c9aa-4908-93a2-9d03181f8a37

**Comment by yusiny** [comment]
@jiwoochris 이거 버전도 알려주세요 이번 작업부터 생긴 버그인가요? 1.0.14

**Comment by jiwoochris** [comment]
버전, 브라우저 업데이트 했습니다!

**Comment by yusiny** [comment]
추정: 화면 확대율에 따라 위치가 다름
